<a href="https://colab.research.google.com/github/nrmalfn/data_science_portfolio/blob/main/Dataset_for_Funnel_and_Cohort_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataset for Funnel and Cohort Analysis

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Dibimbing_assignment/assignment_SG/Assignment Datasets Funnel Cohort.xlsx')

In [ ]:
df.head()

,event_id,user_id,age,gender,city,country,session_id,sequence_number,created_at,browser,traffic_source,event_type
0,555311,42922.0,46.0,M,Bogatynia,Poland,f65f7f3f-1078-45da-a7af-2dd41a894e5d,3,2023-01-19 22:54:38 UTC,Other,Email,cart
1,714816,55343.0,16.0,M,Bogatynia,Poland,cc3509fc-641b-4632-aca7-4949209b9afb,4,2023-11-26 17:12:19 UTC,Safari,Email,cart
2,464405,35775.0,46.0,F,Bogatynia,Poland,16f8b065-9b2e-47bf-b8e7-793060cfbe04,9,2023-09-27 02:46:04 UTC,Firefox,Adwords,cart
3,649908,50243.0,47.0,M,Bogatynia,Poland,8b145bdf-4ddd-473a-8095-c35504afa112,3,2023-04-16 08:50:42 UTC,Chrome,Adwords,cart
4,874098,67437.0,30.0,M,Zgorzelec,Poland,4871ce1f-0b5c-446d-aa7c-016c959cbe56,3,2023-05-18 04:24:49 UTC,Firefox,Email,cart

In [ ]:
excel_data = pd.ExcelFile('/content/drive/MyDrive/Dibimbing_assignment/assignment_SG/Assignment Datasets Funnel Cohort.xlsx')

In [ ]:
excel_data.sheet_names

['Events', 'Sales']

### Dataset for Funnel Analysis

In [ ]:
df_Events = excel_data.parse(excel_data.sheet_names[0])

In [ ]:
df_Events.head()

,event_id,user_id,age,gender,city,country,session_id,sequence_number,created_at,browser,traffic_source,event_type
0,555311,42922.0,46.0,M,Bogatynia,Poland,f65f7f3f-1078-45da-a7af-2dd41a894e5d,3,2023-01-19 22:54:38 UTC,Other,Email,cart
1,714816,55343.0,16.0,M,Bogatynia,Poland,cc3509fc-641b-4632-aca7-4949209b9afb,4,2023-11-26 17:12:19 UTC,Safari,Email,cart
2,464405,35775.0,46.0,F,Bogatynia,Poland,16f8b065-9b2e-47bf-b8e7-793060cfbe04,9,2023-09-27 02:46:04 UTC,Firefox,Adwords,cart
3,649908,50243.0,47.0,M,Bogatynia,Poland,8b145bdf-4ddd-473a-8095-c35504afa112,3,2023-04-16 08:50:42 UTC,Chrome,Adwords,cart
4,874098,67437.0,30.0,M,Zgorzelec,Poland,4871ce1f-0b5c-446d-aa7c-016c959cbe56,3,2023-05-18 04:24:49 UTC,Firefox,Email,cart

In [ ]:
df_Events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418279 entries, 0 to 418278
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   event_id         418279 non-null  int64
 1   user_id          265687 non-null  float64
 2   age              265687 non-null  float64
 3   gender           265687 non-null  object
 4   city             262839 non-null  object
 5   country          265687 non-null  object
 6   session_id       418279 non-null  object
 7   sequence_number  418279 non-null  int64
 8   created_at       418279 non-null  object
 9   browser          418279 non-null  object
 10  traffic_source   418279 non-null  object
 11  event_type       418279 non-null  object
dtypes: float64(2), int64(2), object(8)
memory usage: 38.3+ MB

In [ ]:
df_Events['created_date'] = pd.to_datetime(df_Events['created_at']).dt.date
df_Events.groupby(['created_date', 'event_type', 'gender']).user_id.nunique()

created_date  event_type  gender
2023-01-01    cart        F         36
                          M         28
              home        F         24
                          M         19
              product     F         36
                                    ..
2023-12-31    home        M         52
              product     F         57
                          M         70
              purchase    F         72
                          M         91
Name: user_id, Length: 2920, dtype: int64

In [ ]:
# Aggregate
df_Funnel = df_Events.groupby(['created_date', 'event_type', 'gender'])['user_id'].nunique().reset_index()

# Rename
df_Funnel.rename(columns={'user_id': 'unique_user_count'}, inplace=True)

df_Funnel.head()

  created_date event_type gender  unique_user_count
0   2023-01-01       cart      F                 36
1   2023-01-01       cart      M                 28
2   2023-01-01       home      F                 24
3   2023-01-01       home      M                 19
4   2023-01-01    product      F                 36

In [ ]:
df_Funnel.to_excel('Funnel_table.xlsx')

### Dataset for Cohort Analysis

In [ ]:
df_Sales = excel_data.parse(excel_data.sheet_names[1])

In [ ]:
df_Sales.head()

,order_items_id,order_id,order_date,user_id,age,gender,product_id,product_name,product_category,product_price,product_cost,item_qty
0,7005,4790,2023-06-09,3802,18,F,8033,Embroidered Capri Set - Sizes: SMMEDLG,Clothing Sets,19.99,11.49,1
1,55182,38050,2023-03-17,30411,37,F,8038,Embroidered Capri Set - Sizes: 1X2X3X4X,Clothing Sets,22.99,13.86,1
2,107743,74517,2023-11-19,59668,28,F,8038,Embroidered Capri Set - Sizes: 1X2X3X4X,Clothing Sets,22.99,13.86,1
3,8139,5591,2023-05-13,4410,64,F,8028,Collections Etc - Autumn Floral V Neck Top And...,Clothing Sets,32.97,20.80,1
4,149787,103464,2023-05-04,82891,37,F,8028,Collections Etc - Autumn Floral V Neck Top And...,Clothing Sets,32.97,20.80,1

In [ ]:
# Aggregate created_at column from Events to Sales

agg_events = df_Events.groupby('user_id', as_index=False).agg(min_date=('created_at', 'min'))
output_table = pd.merge(df_Sales, agg_events, on='user_id', how='left')

In [ ]:
output_table.head()

,order_items_id,order_id,order_date,user_id,age,gender,product_id,product_name,product_category,product_price,product_cost,item_qty,min_date
0,7005,4790,2023-06-09,3802,18,F,8033,Embroidered Capri Set - Sizes: SMMEDLG,Clothing Sets,19.99,11.49,1,2023-06-08 09:42:23 UTC
1,55182,38050,2023-03-17,30411,37,F,8038,Embroidered Capri Set - Sizes: 1X2X3X4X,Clothing Sets,22.99,13.86,1,2023-03-15 05:13:10 UTC
2,107743,74517,2023-11-19,59668,28,F,8038,Embroidered Capri Set - Sizes: 1X2X3X4X,Clothing Sets,22.99,13.86,1,2023-11-19 00:48:50 UTC
3,8139,5591,2023-05-13,4410,64,F,8028,Collections Etc - Autumn Floral V Neck Top And...,Clothing Sets,32.97,20.80,1,2023-05-11 09:13:22 UTC
4,149787,103464,2023-05-04,82891,37,F,8028,Collections Etc - Autumn Floral V Neck Top And...,Clothing Sets,32.97,20.80,1,2023-05-02 11:33:39 UTC

In [ ]:
output_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37354 entries, 0 to 37353
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_items_id    37354 non-null  int64
 1   order_id          37354 non-null  int64
 2   order_date        37354 non-null  datetime64[ns]
 3   user_id           37354 non-null  int64
 4   age               37354 non-null  int64
 5   gender            37354 non-null  object
 6   product_id        37354 non-null  int64
 7   product_name      37351 non-null  object
 8   product_category  37354 non-null  object
 9   product_price     37354 non-null  float64
 10  product_cost      37354 non-null  float64
 11  item_qty          37354 non-null  int64
 12  min_date          37354 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(6), object(4)
memory usage: 3.7+ MB

In [ ]:
output_table['min_date'] = pd.to_datetime(output_table['min_date'], errors='coerce')
output_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37354 entries, 0 to 37353
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_items_id    37354 non-null  int64
 1   order_id          37354 non-null  int64
 2   order_date        37354 non-null  datetime64[ns]
 3   user_id           37354 non-null  int64
 4   age               37354 non-null  int64
 5   gender            37354 non-null  object
 6   product_id        37354 non-null  int64
 7   product_name      37351 non-null  object
 8   product_category  37354 non-null  object
 9   product_price     37354 non-null  float64
 10  product_cost      37354 non-null  float64
 11  item_qty          37354 non-null  int64
 12  min_date          37354 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), float64(2), int64(6), object(3)
memory usage: 3.7+ MB

In [ ]:
output_table['min_date'] = output_table['min_date'].dt.date
output_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37354 entries, 0 to 37353
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_items_id    37354 non-null  int64
 1   order_id          37354 non-null  int64
 2   order_date        37354 non-null  datetime64[ns]
 3   user_id           37354 non-null  int64
 4   age               37354 non-null  int64
 5   gender            37354 non-null  object
 6   product_id        37354 non-null  int64
 7   product_name      37351 non-null  object
 8   product_category  37354 non-null  object
 9   product_price     37354 non-null  float64
 10  product_cost      37354 non-null  float64
 11  item_qty          37354 non-null  int64
 12  min_date          37354 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(6), object(4)
memory usage: 3.7+ MB

In [ ]:
output_table['min_date'] = pd.to_datetime(output_table['min_date'], errors='coerce')
output_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37354 entries, 0 to 37353
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_items_id    37354 non-null  int64
 1   order_id          37354 non-null  int64
 2   order_date        37354 non-null  datetime64[ns]
 3   user_id           37354 non-null  int64
 4   age               37354 non-null  int64
 5   gender            37354 non-null  object
 6   product_id        37354 non-null  int64
 7   product_name      37351 non-null  object
 8   product_category  37354 non-null  object
 9   product_price     37354 non-null  float64
 10  product_cost      37354 non-null  float64
 11  item_qty          37354 non-null  int64
 12  min_date          37354 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(6), object(3)
memory usage: 3.7+ MB

In [ ]:
output_table['cohort_date'] = output_table['order_date'] - output_table['min_date']
output_table['cohort_date'] = output_table['cohort_date'].dt.days

In [ ]:
output_table.head()

,order_items_id,order_id,order_date,user_id,age,gender,product_id,product_name,product_category,product_price,product_cost,item_qty,min_date,cohort_date
0,7005,4790,2023-06-09,3802,18,F,8033,Embroidered Capri Set - Sizes: SMMEDLG,Clothing Sets,19.99,11.49,1,2023-06-08,1
1,55182,38050,2023-03-17,30411,37,F,8038,Embroidered Capri Set - Sizes: 1X2X3X4X,Clothing Sets,22.99,13.86,1,2023-03-15,2
2,107743,74517,2023-11-19,59668,28,F,8038,Embroidered Capri Set - Sizes: 1X2X3X4X,Clothing Sets,22.99,13.86,1,2023-11-19,0
3,8139,5591,2023-05-13,4410,64,F,8028,Collections Etc - Autumn Floral V Neck Top And...,Clothing Sets,32.97,20.80,1,2023-05-11,2
4,149787,103464,2023-05-04,82891,37,F,8028,Collections Etc - Autumn Floral V Neck Top And...,Clothing Sets,32.97,20.80,1,2023-05-02,2

In [ ]:
output_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37354 entries, 0 to 37353
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_items_id    37354 non-null  int64
 1   order_id          37354 non-null  int64
 2   order_date        37354 non-null  datetime64[ns]
 3   user_id           37354 non-null  int64
 4   age               37354 non-null  int64
 5   gender            37354 non-null  object
 6   product_id        37354 non-null  int64
 7   product_name      37351 non-null  object
 8   product_category  37354 non-null  object
 9   product_price     37354 non-null  float64
 10  product_cost      37354 non-null  float64
 11  item_qty          37354 non-null  int64
 12  min_date          37354 non-null  datetime64[ns]
 13  cohort_date       37354 non-null  int64
dtypes: datetime64[ns](2), float64(2), int64(7), object(3)
memory usage: 4.0+ MB

In [ ]:
output_table.to_excel('Cohort_table.xlsx')